#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META		
add lib src/cmdliner.mli
add lib src/cmdliner.cmti
add lib src/cmdliner.cmi
add lib src/cmdliner.cmx
add lib src/cmdliner.cma
add lib src/cmdliner.a
add lib src/cmdliner.cmxa
add lib src/cmdliner.cmxs

add doc README.md
add doc CHANGES.md
add doc test/chorus.ml
add doc test/cp_ex.ml 
add doc test/darcs_ex.ml
add doc test/revolt.ml
add doc test/rm_ex.ml
add doc test/tail_ex.ml

build
install cmdliner
